language: scala

scala:
  - 2.11.11

jdk:
  - openjdk8

env:
  global:
    - secure: "RdZfbzf5Oja9oVLCvl7Ej+j9DpRPM4OFZ3pP+TYPqQ1DVfrhA2W2AjpYt8QVXeagVCFbJu48Og/sImkoQnkgh8+/7IGPnX29weEFsHZhf8FA1E7Gf1o1HU5YhJuCOsNOR9xG+1tRHR/+gKOwP1VyGugUhrSwNOuYGOr6yQ1JYfU="
    - secure: "ezhPWkY6EjHsQnqRSEghdsmkzbeB4tBiekfNTH+5E6TmO9qiplasJELa8Bqvpmnl7nCjFFn1BrFBsdxCRyApIiPxxV8KAE3w1whmNGsYdYvNFJo9xqs0BG5CEDIqnT78LstSJVFFKwytLB8Fus1dN17LbV/80+iIx1iJkoSVc7k="

before_script:
  - if [ $TRAVIS_SECURE_ENV_VARS == true ]; then
    svn --username $SVN_USERNAME --password $SVN_PASSWORD --non-interactive co http://source.gemini.edu/software/ocs-credentials $TRAVIS_BUILD_DIR/ocs-credentials;
    ls $TRAVIS_BUILD_DIR;
    bash $TRAVIS_BUILD_DIR/ocs-credentials/trunk/link.sh -v $TRAVIS_BUILD_DIR;
    fi
  - if [ $TRAVIS_SECURE_ENV_VARS == false ]; then
    cp $TRAVIS_BUILD_DIR/project/OcsCredentials.scala.template $TRAVIS_BUILD_DIR/project/OcsCredentials.scala;
    fi

script:
  - sudo chmod +x /usr/local/bin/sbt
  - sbt -q -J-Djava.util.logging.config.file=logging.properties -J-Dedu.gemini.ocs.build.ping ++$TRAVIS_SCALA_VERSION test:compile test
  - sbt -q -J-Djava.util.logging.config.file=logging.properties -J-Dedu.gemini.ocs.build.ping ++2.13.1 bundle_edu_gemini_model_p1_pdf/publishLocal bundle_edu_gemini_model_p1_targetio/publishLocal bundle_edu_gemini_model_p1/publishLocal bundle_edu_gemini_pot/publishLocal bundle_edu_gemini_seqexec_odb/publishLocal bundle_edu_gemini_shared_skyobject/publishLocal bundle_edu_gemini_shared_util/publishLocal bundle_edu_gemini_spModel_core/publishLocal bundle_edu_gemini_spModel_io/publishLocal bundle_edu_gemini_spModel_pio/publishLocal bundle_edu_gemini_spModel_smartgcal/publishLocal bundle_edu_gemini_util_javax_mail/publishLocal bundle_edu_gemini_util_osgi/publishLocal bundle_edu_gemini_util_pdf/publishLocal bundle_edu_gemini_util_skycalc/publishLocal bundle_edu_gemini_util_ssl/publishLocal bundle_edu_gemini_util_ssl_apache/publishLocal bundle_edu_gemini_wdba_session_client/publishLocal bundle_edu_gemini_wdba_shared/publishLocal bundle_edu_gemini_wdba_xmlrpc_api/publishLocal bundle_jsky_coords/publishLocal bundle_jsky_util/publishLocal bundle_jsky_util_gui/publishLocal bundle_edu_gemini_epics_acm/publishLocal

cache:
  directories:
    - $HOME/.sbt/0.13/dependency
    - $HOME/.sbt/boot/scala*
    - $HOME/.sbt/launchers
    - $HOME/.ivy2/cache
    - $HOME/.nvm

before_cache:
  - du -h -d 1 $HOME/.ivy2/cache
  - du -h -d 2 $HOME/.sbt/
  - find $HOME/.sbt -name "*.lock" -type f -delete
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete
